stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    - data/raw
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - src/feature_engineering.py
    - data/interim
    params:
    - feature_engineering.max_features
    outs:
    - data/processed

  model_building:
    cmd: python src/model_building.py
    deps:
    - src/model_building.py
    - data/processed
    params:
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - src/model_evaluation.py
    - models/model.pkl
    outs:
    - models/reports/metrics.json